{
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "mocha": true,
    "jquery": true,
    "commonjs": true
  },
  "globals": {
    "initialState": false,
    "appConfig": false,
    "OrganisationsInitialState": false
  },
  "ecmaFeatures": {
    "arrowFunctions": true,
    "binaryLiterals": true,
    "blockBindings": true,
    "classes": true,
    "defaultParams": true,
    "destructuring": true,
    "forOf": true,
    "generators": true,
    "modules": true,
    "objectLiteralComputedProperties": true,
    "objectLiteralDuplicateProperties": true,
    "objectLiteralShorthandMethods": true,
    "objectLiteralShorthandProperties": true,
    "octalLiterals": true,
    "regexUFlag": true,
    "regexYFlag": true,
    "spread": true,
    "superInFunctions": true,
    "templateStrings": true,
    "unicodeCodePointEscapes": true,
    "globalReturn": true,
    "jsx": true
  },
  "rules": {
    "no-undef": 2,
    "comma-dangle": 2,
    "no-cond-assign": 2,
    "no-console": 2,
    "no-constant-condition": 2,
    "no-control-regex": 2,
    "no-debugger": 2,
    "no-dupe-args": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty-character-class": 2,
    "no-empty": 2,
    "no-ex-assign": 2,
    "no-extra-boolean-cast": 2,
    "no-extra-semi": 2,
    "no-func-assign": 2,
    "no-inner-declarations": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 2,
    "no-negated-in-lhs": 2,
    "no-obj-calls": 2,
    "no-regex-spaces": 2,
    "no-sparse-arrays": 2,
    "no-unexpected-multiline": 2,
    "no-unreachable": 2,
    "use-isnan": 2,
    "valid-jsdoc": 2,
    "valid-typeof": 2,
    "brace-style": [2, "1tbs", { "allowSingleLine": false }],
    "camelcase": [2, {"properties": "always"}],
    "comma-spacing": [2, {"before": false, "after": true}],
    "comma-style": [2, "last"],
    "consistent-this": [2, "that"],
    "eol-last": 2,
    "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
    "new-cap": 2,
    "new-parens": 2,
    "no-array-constructor": 2,
    "no-lonely-if": 2,
    "no-multiple-empty-lines": [2, {"max": 1}],
    "no-nested-ternary": 2,
    "no-new-object": 2,
    "semi-spacing": [2, {"before": false, "after": true}],
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    "no-underscore-dangle": 2,
    "operator-assignment": [2, "always"],
    "quote-props": [2, "consistent-as-needed"],
    "quotes": [2, "single"],
    "semi": [2, "always"],
    "space-before-function-paren": [2, "never"],
    "space-after-keywords": 2,
    "space-before-blocks": 2,
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2,
    "space-return-throw-case": 2,
    "space-unary-ops": [2, { "words": true, "nonwords": false }],
    "spaced-comment": [2, "always"],
    "wrap-regex": 2
  }
}
